name:                scirate-cli
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/silky/scirate-cli#readme
license:             BSD3
author:              Noon van der Silk
maintainer:          noonsilk@gmail.com
copyright:           Noon van der Silk
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - brick
  - bytestring
  - conduit
  - containers
  - directory
  - dotenv
  - filepath
  - html-conduit
  - http-conduit
  - http-types
  - microlens
  - microlens-th
  - optparse-applicative
  - resourcet
  - text
  - time
  - vty
  - xml-conduit

executables:
  scirate-cli:
    ghc-options:      -threaded
    source-dirs:      src
    main:             Main.hs
